/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas.Relatorios;

import Controller.ControleGestorService;
import Controller.RelatoriosService;
import Model.Usuario;
import Telas.dialogs.RelatoriosDialog;
import Telas.TelaAdministrador;
        
/**
 *
 * @author massas
 */
        
import Controller.CaixaService;
import Controller.StockService;
import Controller.VendasService;
public class TelaRelatorios extends javax.swing.JFrame {
    private Usuario usuarioLogado;
    private ControleGestorService controleGestorService;
    private VendasService vendasService;
    private StockService stockService;
    private CaixaService caixaService;
    private RelatoriosService relatoriosService;
    /**
     * Creates new form TelaRelatorios
     */
    public TelaRelatorios(Usuario usuario, ControleGestorService controleGestorService) {
        this.usuarioLogado = usuario;
        this.controleGestorService = controleGestorService;
        this.vendasService = new VendasService();
        this.stockService = new StockService();
        this.caixaService = new CaixaService(vendasService);
        this.relatoriosService = new RelatoriosService(vendasService, stockService, caixaService, controleGestorService);
        
        initComponents();
    }

    public TelaRelatorios(Usuario usuarioLogado, RelatoriosService relatoriosService, ControleGestorService controleGestorService) {
        this.usuarioLogado = usuarioLogado;
        this.relatoriosService = relatoriosService;
        this.controleGestorService = controleGestorService;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RVendasBtn = new javax.swing.JButton();
        RClientesBtn = new javax.swing.JButton();
        RPagamentosBtn = new javax.swing.JButton();
        RConsolidadoBtn = new javax.swing.JButton();
        VoltarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        RVendasBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/IconsDB/icons8-ac╠ºo╠âes-64.png"))); // NOI18N
        RVendasBtn.setText("Relatorio de Vendas");
        RVendasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RVendasBtnActionPerformed(evt);
            }
        });

        RClientesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/IconsDB/icons8-ac╠ºo╠âes-64.png"))); // NOI18N
        RClientesBtn.setText("Relatorio de Clientes");
        RClientesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RClientesBtnActionPerformed(evt);
            }
        });

        RPagamentosBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/IconsDB/icons8-ac╠ºo╠âes-64.png"))); // NOI18N
        RPagamentosBtn.setText("Relatorio de Pagamentos");
        RPagamentosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RPagamentosBtnActionPerformed(evt);
            }
        });

        RConsolidadoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/IconsDB/icons8-ac╠ºo╠âes-64.png"))); // NOI18N
        RConsolidadoBtn.setText("Relatorio Consolidado");
        RConsolidadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RConsolidadoBtnActionPerformed(evt);
            }
        });

        VoltarBtn.setText("Voltar");
        VoltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RPagamentosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RVendasBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RConsolidadoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RClientesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VoltarBtn)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RVendasBtn)
                    .addComponent(RClientesBtn))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RPagamentosBtn)
                    .addComponent(RConsolidadoBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(VoltarBtn)
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RVendasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RVendasBtnActionPerformed
        relatorioVendas();
    }//GEN-LAST:event_RVendasBtnActionPerformed

    private void RConsolidadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RConsolidadoBtnActionPerformed
        relatorioConsolidado();
    }//GEN-LAST:event_RConsolidadoBtnActionPerformed

    private void RClientesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RClientesBtnActionPerformed
        relatorioClientes();
    }//GEN-LAST:event_RClientesBtnActionPerformed

    private void RPagamentosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RPagamentosBtnActionPerformed
        relatorioPagamentos();
    }//GEN-LAST:event_RPagamentosBtnActionPerformed

    private void VoltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBtnActionPerformed
        TelaAdministrador telaAdmin = new TelaAdministrador(usuarioLogado, controleGestorService);
        telaAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VoltarBtnActionPerformed

    private void relatorioVendas() {
        RelatoriosDialog dialog = new RelatoriosDialog(this, relatoriosService);
        dialog.setVisible(true);
    }
    
    private void relatorioClientes() {
        RelatoriosDialog dialog = new RelatoriosDialog(this, relatoriosService);
        dialog.setVisible(true);
    }
    
    private void relatorioPagamentos() {
        RelatoriosDialog dialog = new RelatoriosDialog(this, relatoriosService);
        dialog.setVisible(true);
    }
    
    private void relatorioConsolidado() {
        RelatoriosDialog dialog = new RelatoriosDialog(this, relatoriosService);
        dialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RClientesBtn;
    private javax.swing.JButton RConsolidadoBtn;
    private javax.swing.JButton RPagamentosBtn;
    private javax.swing.JButton RVendasBtn;
    private javax.swing.JButton VoltarBtn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
